# Cloud Run サービス (main) と Cloud Run ジョブ (vectorize-job) をデプロイする構成
steps:
# --- 1. 司令塔 (main-service) のビルド＆デプロイ ---
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Main Service Image'
  args: ['build', '-t', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}', '.', '-f', 'Dockerfile']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Main Service Image'
  args: ['push', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy Main Service'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
    - '--region=${_DEPLOY_REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=marketing-automation@marketing-automation-461305.iam.gserviceaccount.com'
    - '--set-env-vars=GCP_PROJECT_ID=${PROJECT_ID},GCS_BUCKET_NAME=embedding_storage,COHERE_API_KEY=${_COHERE_API_KEY},VECTORIZE_JOB_NAME=cohere-rag-vectorize-job,GCP_REGION=${_DEPLOY_REGION}'

# --- 2. 作業員 (vectorize-job) のビルド＆デプロイ ---
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Vectorize Job Image'
  args: ['build', '-t', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_JOB_NAME_VECTORIZE}:${COMMIT_SHA}', '.', '-f', 'Dockerfile.job']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Vectorize Job Image'
  args: ['push', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_JOB_NAME_VECTORIZE}:${COMMIT_SHA}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy Vectorize Job'
  entrypoint: gcloud
  args:
    - 'run'
    - 'jobs'
    - 'replace'
    - '${_JOB_NAME_VECTORIZE}'
    - '--image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_JOB_NAME_VECTORIZE}:${COMMIT_SHA}'
    - '--region=${_DEPLOY_REGION}'
    - '--service-account=marketing-automation@marketing-automation-461305.iam.gserviceaccount.com'
    - '--set-env-vars=GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},COHERE_API_KEY=${_COHERE_API_KEY}'
    - '--tasks=1'
    - '--max-retries=1'

images:
- '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
- '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_JOB_NAME_VECTORIZE}:${COMMIT_SHA}'

