# Cloud Run サービス (main) と Cloud Run ジョブ (vectorize-job) をデプロイする構成
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# --- 1. 司令塔 (main-service) のビルド＆デプロイ ---
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Main Service Image'
  args: ['build', '-t', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}', '.', '-f', 'Dockerfile']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Main Service Image'
  args: ['push', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy Main Service'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
    - '--region=${_DEPLOY_REGION}'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=${_SERVICE_ACCOUNT_EMAIL}'
    - '--update-env-vars=GCP_PROJECT_ID=${PROJECT_ID},GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},COHERE_API_KEY=${_COHERE_API_KEY},VECTORIZE_JOB_NAME=${_JOB_NAME_VECTORIZE},GCP_REGION=${_DEPLOY_REGION},ENVIRONMENT=${_ENVIRONMENT},GOOGLE_SHEETS_ID=${_GOOGLE_SHEETS_ID}'
    - '--memory=1Gi'

# --- 2. 作業員 (vectorize-job) のビルド＆デプロイ ---
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Vectorize Job Image'
  args: ['build', '-t', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_JOB_NAME_VECTORIZE}:${COMMIT_SHA}', '.', '-f', 'Dockerfile.job']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Vectorize Job Image'
  args: ['push', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_JOB_NAME_VECTORIZE}:${COMMIT_SHA}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy Vectorize Job'
  entrypoint: gcloud
  args:
    - 'run'
    - 'jobs'
    - 'update'
    - '${_JOB_NAME_VECTORIZE}'
    - '--image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_JOB_NAME_VECTORIZE}:${COMMIT_SHA}'
    - '--region=${_DEPLOY_REGION}'
    - '--service-account=${_SERVICE_ACCOUNT_EMAIL}'
    - '--update-env-vars=GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},COHERE_API_KEY=${_COHERE_API_KEY},ENVIRONMENT=${_ENVIRONMENT}'
    - '--task-timeout=36000'
    - '--parallelism=1'
    - '--max-retries=0'
    - '--memory=2Gi'
    - '--cpu=2'

images:
- '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
- '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_JOB_NAME_VECTORIZE}:${COMMIT_SHA}'
