# Cloud Run Job configuration for Scheduler
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: scheduler-job
  labels:
    cloud.googleapis.com/location: asia-northeast1
  annotations:
    run.googleapis.com/cpu-throttling: 'false'
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          timeoutSeconds: 3600  # 1 hour timeout
          containers:
          - image: SCHEDULER_IMAGE_PLACEHOLDER
            name: scheduler
            resources:
              limits:
                cpu: '2'
                memory: 4Gi
              requests:
                cpu: '1'
                memory: 2Gi
            env:
            - name: ENVIRONMENT
              value: 'production'
            - name: GCS_BUCKET_NAME
              value: 'embedding_storage'
            - name: COHERE_API_KEY
              value: 'COHERE_API_KEY_PLACEHOLDER'
            - name: MAX_WORKERS
              value: '3'