# Cloud Run Job configuration for Scheduler
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: scheduler-job
spec:
  template:
    spec:
      template:
        spec:
          containers:
          - image: SCHEDULER_IMAGE_PLACEHOLDER
            env:
            - name: ENVIRONMENT
              value: 'production'
            - name: GCS_BUCKET_NAME
              value: 'embedding_storage'
            - name: COHERE_API_KEY
              value: 'COHERE_API_KEY_PLACEHOLDER'